# Generated by Django 5.0 on 2024-01-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('restro_id', models.IntegerField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('rating', models.FloatField(blank=True, help_text='Restaurant Rating', null=True)),
                ('delivering_now', models.BooleanField(default=False)),
            ],
        ),
    ]
